### ISSUE TITLE
Funky flowmeter readings depending on start-up procedure

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#5]
Hi Bryerton,
For our board in Napoli, I discovered that the readings from the flowmeter ("get flow") are bad if the board is first connected to serial/USB, then powered on. Readings will either be something like -218 or >+210. The issue is reproducible for me. I have not figured out how to recover reliable readout from the flowmeter once this state is reached. The only solution I know of is to power off and do a proper cold start: power the board first, then plug in USB/serial to computer. Do you see this behavior? Could you maybe add a warning when serial communication is established and flow readings are wacky? 
thanks

**Comment by bryerton** [comment]
I will look into this! We just got our board here, so I'll test this
behavior today

**Comment by bryerton** [comment]
I see this as well, I also note that the first reading is always bad,
regardless of what the order you plug in the USB cable is

**Comment by bryerton** [comment]
It's because the code appears to not recover from failure, since the USB
cable is in, the ESP32 is powered, and it runs its startup sequence and
gets a failure from the flow sensor. It never recovers the flow sensor
after that.

This won't happen under normal circumstances as the MVM powers up
everything simultaneously, but in our test setup where we've bypassed the
RPi it's possible.

**Comment by leyton-cern** [comment]
Ideally, "get flow" or "get all" would init the flow sensor if undefined. The crappy part is in this mode, "get flow" will return -218, but "get all" returns something close to 0 and the volume readings are also wacky.

**Comment by bryerton** [comment]
I'm going to close this issue, as it's only fixable in the MVMFirmware itself, there is no available work-around performable in the mvm-control.
