### ISSUE TITLE
First breath after changing board settings

### ISSUE THREAD

**Issue by leyton-cern** [MechanicalVentilatorMilano/mvm-control#6]
Hi Bryerton,
When running clog and loading a board config using the -u option, I noticed that the first breath of the ventilator seems to use the settings previously stored on the board. In case you want to try to reproduce this issue, it is most easily evident when changing the breathing rate. This only affects the first breath, as far as I can tell. 
I suppose the settings are being loaded in the order they appear in the json files, which means that the run starts before the run parameters are set. I think you want to change the order so that "set run X" is loaded after the other settings. Maybe even execute "set run 1" last, but "set run 0" first. Do you agree?

**Comment by bryerton** [comment]
Do you think the logger should control the run bit? I could have
mvm-control set run to 0 before loading a config, 1 when its ready to run,
and 0 when its done logging. Or should it leave it running? (I can also add
an optional flag for this behavior)

**Comment by leyton-cern** [comment]
Default logger should apply the run bit in the config. Optional "override" option would ignore what is in log file, start run with logging and end run when finished logging. I would personally use override option 95% of the time, but still think any code that overrides what is in config should require an additional flag.

**Comment by bryerton** [comment]
I think the 'override' mode should be the default, and the 'run' bit should be removed from the config settings. No logging can take place with the 'run' bit set to zero, so it seems redundant, I also want to avoid having the 'save' and 'load' functions changing the run state, in order to protect from accidental on when loading a config prior to starting a log. 

Since the mvm-control takes control of the ESP32's serial link, and we always want to have a run on when logging, I've changed the default behavior to turn on a run on start, and turn it off on exit. This feels safer, I've can add an override to leave an MVM run on before and after a log run.

**Comment by leyton-cern** [comment]
sounds good to me!

**Comment by leyton-cern** [comment]
Hi Bryerton,
The changes you made yesterday are much appreciated, thank you. Unfortunately, the "first breath" issue is not yet resolved in the new version. I don't understand why. Looking at the code, it should work, but maybe some additional sleep is needed. I hope you can reproduce the issue because it might require some tuning.

**Comment by bryerton** [comment]
Might be fixed now, updated to 1.3.3. Now after the settings are ... set,
then it waits for a couple seconds, then the logging starts.

**Comment by leyton-cern** [comment]
5 s might be overkill! 1-2 works for me.

**Comment by bryerton** [comment]
I can adjust it down
